### ISSUE TITLE
امکان دارد یک نوتیفیکیشن نیز به این اپ اضافه کنید؟

### ISSUE THREAD

**Issue by 0xRustlang** [ebraminio/fixed-clock#1]
با سلام
این اپ فوق‌العاده است

امکان دارد یک نوتیفیکیشن نیز به آن اضافه کنید که ساعت را درآن بزرگ نشان دهد؟ (محتوای نوتیفیکیشن منظورم است)

آن نوتیفیکیشن بسیار برای دیدن ساعت صحیح از لاک اسکرین کاربردی است.

باتشکر فراوان

**Comment by ebraminio** [comment]
سلام گرامی، این یک پروژهٔ چندان جدی نیست، اول خواستم اینکار را انجام دهم و حتی دست‌به‌کد شدم ولی جزئیات زیادی دارد، باید برای اجرا برنامه در startup گوشی یک broadcast reciever قرار داد، باید به‌شیوه‌ای مثل workmanager هر چندوقت یک بار تجدید کرد یحتمل، باید دسترسی اعلان برای اندرویدهای جدیدتر گرفت و آنچه که ایجاد اعلان را ساده‌تر می‌کند در اندروید شما (۲۴) وجود ندارد

<img width="887" alt="image" src="https://github.com/ebraminio/fixed-clock/assets/833473/36413328-a7f5-432c-baeb-c569d4b776db">

که نیاز است کتابخانه‌ای برای آن بیافزایم که کمی با اهداف اولیه این تجربه تفاوت دارد به خاطر همین شاید بهتر است در پروژهٔ دیگری یا یک فورک در نظر گرفته شود، ممنونم 😊

**Comment by 0xRustlang** [comment]
> سلام گرامی، این یک پروژهٔ چندان جدی نیست، اول خواستم اینکار را انجام دهم و حتی دست‌به‌کد شدم ولی جزئیات زیادی دارد، باید برای اجرا برنامه در startup گوشی یک broadcast reciever قرار داد، باید به‌شیوه‌ای مثل workmanager هر چندوقت یک بار تجدید کرد یحتمل، باید دسترسی اعلان برای اندرویدهای جدیدتر گرفت و آنچه که ایجاد اعلان را ساده‌تر می‌کند در اندروید شما (۲۴) وجود ندارد
> <img alt="image" width="887" src="https://private-user-images.githubusercontent.com/833473/316310227-36413328-a7f5-432c-baeb-c569d4b776db.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEyODc5NjksIm5iZiI6MTcxMTI4NzY2OSwicGF0aCI6Ii84MzM0NzMvMzE2MzEwMjI3LTM2NDEzMzI4LWE3ZjUtNDMyYy1iYWViLWM1NjlkNGI3NzZkYi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyNFQxMzQxMDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lZDU3ZGE3MmM0NjQzNGJkY2JlNzY2MjY5ODVkY2YxMTM3YzEyMTNmNTQ2MTk0NWE3NTgzYjI2OTgxODQzMTFiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.E_U8bgO4lR_VXw6dNrOMJjcN-eV2bPH8A6OYK1mPPrU">
> 
> که نیاز است کتابخانه‌ای برای آن بیافزایم که کمی با اهداف اولیه این تجربه تفاوت دارد به خاطر همین شاید بهتر است در پروژهٔ دیگری یا یک فورک در نظر گرفته شود، ممنونم 😊

شرمنده، البته گوشی قدیمی من api لول 27 است

و گوشی یکی از آشنایان api لول 31
است.

برای اینها هم برایتان سخت است؟

در هر صورت متشکرم
همین ویجت هم فوق‌العاده است و بسیار استفاده من از گوشی را نسبت به سال قبل آسان تر میکند

بسیار متشکرم از شما

**Comment by ebraminio** [comment]
الآن فهمیدم شما را با شخص دیگری که APIی ۲۴ داشت اشتباه گرفته‌ام 😅 خوشبختانه کدی که در حال انجام بودم را پاک نکرده‌ام هنوز، در حال بررسی‌ام، راستی می‌توانید به همین آی‌دی در تلگرام پیام دهید؟ ممنونم 😊

**Comment by ebraminio** [comment]
این نسخه اعلان هم دارد https://github.com/ebraminio/fixed-clock/actions/runs/8411158558/artifacts/1353830220 ولی با روشن شدن دستگاه نمی‌آید و فعلاً هر دفعه آن با روشن کردن دستگاه باز کنید تا ببینیم چه می‌شود، ممنون از پیشنهاد جالبتان 😊

**Comment by 0xRustlang** [comment]
> الآن فهمیدم شما را با شخص دیگری که APIی ۲۴ داشت اشتباه گرفته‌ام 😅 خوشبختانه کدی که در حال انجام بودم را پاک نکرده‌ام هنوز، در حال بررسی‌ام، راستی می‌توانید به همین آی‌دی در تلگرام پیام دهید؟ ممنونم 😊

سلام
بله حتما
البته من تلگرامم همیشه آنلاین نیست و عملا ایمیل نوتیفیکیشن گیت هاب و تلگرام را همزمان دریافت میکنم

اگر نیاز است اکنون پیام میدهم

**Comment by 0xRustlang** [comment]
> این نسخه اعلان هم دارد https://github.com/ebraminio/fixed-clock/actions/runs/8411158558/artifacts/1353830220 ولی با روشن شدن دستگاه نمی‌آید و فعلاً هر دفعه آن با روشن کردن دستگاه باز کنید تا ببینیم چه می‌شود، ممنون از پیشنهاد جالبتان 😊

بسیار ممنونم
روی دستگاه های مختلف تست کردم و عالی است

یک دنیا تشکر
ممنون از شما که این لطف را به من کردید
